language: cpp

compiler:
  - gcc

dist: trusty

sudo: false

before_install:
  - add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - apt-get update

install:
  - apt-get install -y cmake
  - apt-get install -y g++-8
  - apt-get install -y gdb
  - update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 1

script: bash build_all.sh
