language: cpp

compiler:
  - gcc

dist: xenial

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update

install:
  - sudo apt-get install -y cmake
  - sudo apt-get install -y g++-8
  - sudo apt-get install -y gdb
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 1

script: bash build_all.sh
